
package introsde.mail.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MailService", targetNamespace = "http://ws.mail.introsde/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MailService {


    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sendMail", targetNamespace = "http://ws.mail.introsde/", className = "introsde.mail.ws.SendMail")
    @ResponseWrapper(localName = "sendMailResponse", targetNamespace = "http://ws.mail.introsde/", className = "introsde.mail.ws.SendMailResponse")
    @Action(input = "http://ws.mail.introsde/MailService/sendMailRequest", output = "http://ws.mail.introsde/MailService/sendMailResponse")
    public int sendMail(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

}
